name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.13
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Set Yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore Yarn cache
        uses: actions/cache@v3.0.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-cache-
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: Lint files, scripts, and types
        run: yarn --silent lint
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.13
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Set Yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore Yarn cache
        uses: actions/cache@v3.0.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-cache-
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: Test units
        run: yarn --silent test:units --coverage --run-in-band
      - name: Publish code coverage report
        uses: codecov/codecov-action@v3.0.0
